// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ME_FakeDLC","status":true,"description":"It reads a file at game launch to set switches and variables and emulate dlc","parameters":{"File name":"dlc.json","Overwrite on load":"false"}}
];
